In [4]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns
from scipy import stats
import warnings 
warnings.filterwarnings('ignore')
plt.style.use('seaborn-v0_8-darkgrid')
sns.set_palette("viridis") 
# 
print("librarys are loded")

librarys are loded

In [5]:
# load ethiopian data
df=pd.read_csv("../data/ethiopia.csv")
df.head()
# to add new colomen Country withe value Ethiopia
df['Country']='Ethiopia'
# df.head()
df[["YEAR","DOY","Country"]]
df.head()

,YEAR,DOY,T2M,T2M_MAX,T2M_MIN,T2M_RANGE,PRECTOTCORR,RH2M,WS2M,WS2M_MAX,PS,QV2M,Country
0,2015,1,11.73,22.75,3.44,19.31,0.0,41.79,2.73,5.07,77.13,4.00,Ethiopia
1,2015,2,12.30,24.01,4.09,19.92,0.0,33.29,2.39,4.19,77.14,3.35,Ethiopia
2,2015,3,12.49,24.17,3.97,20.20,0.0,33.83,1.77,2.76,77.11,3.43,Ethiopia
3,2015,4,14.08,23.78,6.90,16.88,0.0,38.84,0.87,1.28,77.07,4.60,Ethiopia
4,2015,5,14.06,23.15,7.32,15.83,0.0,47.07,1.34,2.14,77.01,5.58,Ethiopia

In [8]:
# add Date column witDOY and value the combination of DOY and YEAR column  
df['DATE']=pd.to_datetime(df['YEAR'].astype(str)+df['DOY'].astype(str).str.zfill(3) ,format="%Y%j")
df[['YEAR','DOY','DATE']].head(11)

    YEAR  DOY       DATE
0   2015    1 2015-01-01
1   2015    2 2015-01-02
2   2015    3 2015-01-03
3   2015    4 2015-01-04
4   2015    5 2015-01-05
5   2015    6 2015-01-06
6   2015    7 2015-01-07
7   2015    8 2015-01-08
8   2015    9 2015-01-09
9   2015   10 2015-01-10
10  2015   11 2015-01-11

In [11]:
df['MONTH']=df["DATE"].dt.month
df[["DATE","MONTH","YEAR"]].head(150)

          DATE  MONTH  YEAR
0   2015-01-01      1  2015
1   2015-01-02      1  2015
2   2015-01-03      1  2015
3   2015-01-04      1  2015
4   2015-01-05      1  2015
..         ...    ...   ...
145 2015-05-26      5  2015
146 2015-05-27      5  2015
147 2015-05-28      5  2015
148 2015-05-29      5  2015
149 2015-05-30      5  2015

[150 rows x 3 columns]